services:
  pg:
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: streamlens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    networks:
      - streamlens-network

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka-data:/var/lib/kafka
    restart: always
    networks:
      - streamlens-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    ports:
      - 2181:2181
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - streamlens-network

  redis:
    image: redis:7.4.1-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - streamlens-network

volumes:
  redis-data:
  pg-data:
  kafka-data:

networks:
  streamlens-network:
    driver: bridge
