version: "3"

vars:
  DB_CONNECTION: postgres://postgres:postgres@localhost:5432/streamlens-dev
  MIGRATIONS_DIR: internal/db/migrations

tasks:
  start-db:
    desc: Start the database
    cmds:
      - docker compose up

  stop-db:
    desc: Stop the database
    cmds:
      - docker compose down

  clean-db:
    desc: Clean up the database
    cmds:
      - docker compose down -v

  migrate-create:
    desc: Create a new migration file
    interactive: true
    cmds:
      - |
        read -p "Enter migration name: " name
        goose -dir {{.MIGRATIONS_DIR}} create $name sql

  migrate-up:
    desc: Apply all pending migrations
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} postgres {{.DB_CONNECTION}} up

  migrate-down:
    desc: Roll back the most recent migration
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} postgres {{.DB_CONNECTION}} down

  migrate-reset:
    desc: Roll back all migrations
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} postgres {{.DB_CONNECTION}} reset

  migrate-status:
    desc: Check current migration status
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} postgres {{.DB_CONNECTION}} status

  generate-sqlc:
    desc: Generate SQLC code
    cmds:
      - sqlc generate

  run-auth:
    desc: Run the auth service
    cmds:
      - air -c cmd/auth/.air.toml

  build-auth:
    desc: Build the auth service
    cmds:
      - go build -o bin/auth cmd/auth/main.go
